version: '3.8'

services:
    app:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - "DB_HOST=127.0.0.1"
            - "DB_PORT=3306"
            - "DB_DATABASE=laravel"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=root"
        depends_on:
            - db

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
